Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,15 +17,15 @@ jobs:
       - run:
           name: SAST
           command: |
-            snyk auth ${SNYK_TOKEN}
-            snyk code test --severity-threshold=high --org=vigneshs1017 --project-name="${CIRCLE_PROJECT_REPONAME}" || STATUS=$?
-            if [ "${{parameters.fail_if_vul}}" = "true" ] && [ "$STATUS" -ne 0 ]; then
-              echo "Build failed due to vulnerabilities"
-              exit 1
-            else
-              echo "Build continues despite vulnerabilities"
-            fi
-            snyk code monitor --org=vigneshs1017 --project-name="${CIRCLE_PROJECT_REPONAME}"
+             snyk auth ${SNYK_TOKEN}
+             snyk code test --severity-threshold=high --org=vigneshs1017 --project-name="${CIRCLE_PROJECT_REPONAME}" || STATUS=$?
+             if [ "<<parameters.fail_if_vul>>" = "true" ] && [ "$STATUS" -ne 0 ]; then
+               echo "Build failed due to vulnerabilities"
+               exit 1
+             else
+               echo "Build continues despite vulnerabilities"
+             fi
+             snyk code monitor --org=vigneshs1017 --project-name="${CIRCLE_PROJECT_REPONAME}"
 
   scan_application:
     parameters:
