Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,14 +11,21 @@ jobs:
         type: boolean
         default: false
     docker:
-      - image: cimg/node:lts
+      - image: snyk/snyk:alpine
     steps:
       - checkout
-      - snyk/scan:
-          token-variable: SNYK_TOKEN
-          severity-threshold: high
-          fail-on-issues: << parameters.fail_if_vul >>
-          additional-arguments: "--org=vigneshs1017"
+      - run:
+          name: SAST
+          command: |
+             snyk auth ${SNYK_TOKEN}
+             snyk code test --severity-threshold=high --project-name="${CIRCLE_PROJECT_REPONAME}-SAST" --report || STATUS=$?
+             if [ "<<parameters.fail_if_vul>>" = "true" ] && [ "$STATUS" -ne 0 ]; then
+               echo "Build failed due to vulnerabilities"
+               exit 1
+             else
+               echo "Build continues despite vulnerabilities"
+             fi
+            
                                        
   scan_application:
     parameters:
